//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;

namespace SampleWebAppApi.Models;

/// <summary>
/// A full menu item response, as well as the franchise info
/// </summary>
public record SamplewebappControllersFullmenuitemgetresponse
{
    public SamplewebappControllersMenuitemresponseitem Item { get; set; }
    public SamplewebappControllersFranchiseinformation Franchise { get; set; }
}
