//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;

namespace SampleWebAppApi.Models;

/// <summary>
/// The response containing the list of restuarants
/// </summary>
public record SamplewebappControllersRestaurantgetresponse
{
    public SamplewebappControllersRestaurantgetresponseitem[] Items { get; set; }
}
