//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;

namespace SampleWebAppApi.Models;

/// <summary>
/// Specific nutrition facts related to protein
/// </summary>
public record SamplewebappControllersProteinnutritionfact
{
    public int ProteinGrams { get; set; }
    public int ProteinMilligrams { get; set; }
}
