//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;

namespace SampleWebAppApi.Models;

/// <summary>
/// A response containing multiple menu items
/// </summary>
public record SamplewebappControllersMenuitemresponse
{
    public SamplewebappControllersMenuitemresponseitem[] Items { get; set; }
    public int TotalCount { get; set; }
}
