//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;

namespace SampleWebApiApi.Models;

/// <summary>
/// A single franchise response item.
/// </summary>
public record FranchiseGetResponseItem
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Slogan { get; set; }
}
