//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;

namespace SampleWebApiApi.Models;

/// <summary>
/// A single menu item
/// </summary>
public record SamplewebapiControllersMenuitemresponseitem
{
    public Guid Id { get; set; }
    public Guid FranchiseId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public SamplewebapiControllersMenutitemnutritionfacts NutritionFacts { get; set; }
}
