//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;

namespace SampleWebApiApi.Models;

/// <summary>
/// A full menu item response, as well as the franchise info
/// </summary>
public record SamplewebapiControllersFullmenuitemgetresponse
{
    public SamplewebapiControllersMenuitemresponseitem Item { get; set; }
    public SamplewebapiControllersFranchiseinformation Franchise { get; set; }
}
