//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using SampleWebAppApi.Models;

namespace SampleWebAppApi;

/// <summary>
/// /// This is a sample web api for testing / demo purposes for Swagabond.
/// </summary>
public interface ISampleWebAppClient
{
    /// <remarks>
    /// GET /api/v1/franchises
    /// </remarks>
    Task<SamplewebappControllersFranchisegetresponseitem[]> GetApiV1FranchisesAsync(Dictionary<string, string> requestHeaders);
    /// <remarks>
    /// GET /api/v1/menuitems
    /// </remarks>
    Task<SamplewebappControllersMenuitemresponse> GetApiV1MenuitemsAsync(Dictionary<string, string> requestHeaders);
    /// <remarks>
    /// POST /api/v1/menuitems
    /// </remarks>
    Task<SamplewebappControllersMenuitemresponseitem> PostApiV1MenuitemsAsync(Dictionary<string, string> requestHeaders, SamplewebappControllersMenutitempostrequest apiV1MenuitemsPostRequest);
    /// <remarks>
    /// GET /api/v1/menuitems/{id}
    /// </remarks>
    Task<SamplewebappControllersMenuitemresponseitem> GetApiV1MenuitemsidAsync(Dictionary<string, string> requestHeaders, Guid id);
    /// <remarks>
    /// GET /api/v1/menuitems/{id}/full
    /// </remarks>
    Task<SamplewebappControllersFullmenuitemgetresponse> GetApiV1MenuitemsidFullAsync(Dictionary<string, string> requestHeaders, Guid id);
    /// <remarks>
    /// GET /api/v1/restaurants
    /// </remarks>
    Task<SamplewebappControllersRestaurantgetresponse> GetApiV1RestaurantsAsync(Dictionary<string, string> requestHeaders);
    /// <remarks>
    /// POST /api/v1/restaurants
    /// </remarks>
    Task<SamplewebappControllersRestaurantgetresponseitem> PostApiV1RestaurantsAsync(Dictionary<string, string> requestHeaders, SamplewebappControllersRestaurantpostrequest apiV1RestaurantsPostRequest);
    /// <remarks>
    /// GET /api/v1/restaurants/{id}
    /// </remarks>
    Task<SamplewebappControllersRestaurantgetresponseitem> GetApiV1RestaurantsidAsync(Dictionary<string, string> requestHeaders, Guid id);
    /// <remarks>
    /// DELETE /api/v1/restaurants/{id}
    /// </remarks>
    Task<string> DeleteApiV1RestaurantsidAsync(Dictionary<string, string> requestHeaders, Guid id);

}
