//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using SampleWebApiApi.Models;

namespace SampleWebApiApi;

/// <summary>
/// This is a sample web api for testing / demo purposes for Swagabond.
/// </summary>
public interface ISampleWebApiClient
{
    /// <remarks>
    /// POST /api/v1/blank
    /// </remarks>
    Task<string> PostApiv1BlankAsync(Dictionary<string, string> requestHeaders);
    /// <remarks>
    /// GET /api/v1/franchises
    /// </remarks>
    Task<FranchiseGetResponseItem[]> GetApiv1FranchisesAsync(Dictionary<string, string> requestHeaders);
    /// <remarks>
    /// GET /api/v1/franchises/{id}
    /// </remarks>
    Task<FranchiseGetResponseItem> GetApiv1FranchisesidAsync(Dictionary<string, string> requestHeaders, Guid id);
    /// <remarks>
    /// GET /api/v1/menuitems
    /// </remarks>
    Task<MenuItemResponse> GetApiv1MenuitemsAsync(Dictionary<string, string> requestHeaders);
    /// <remarks>
    /// POST /api/v1/menuitems
    /// </remarks>
    Task<MenuItemResponseItem> PostApiv1MenuitemsAsync(Dictionary<string, string> requestHeaders, MenutItemPostRequest apiv1MenuitemsPostRequest);
    /// <remarks>
    /// GET /api/v1/menuitems/{id}
    /// </remarks>
    Task<MenuItemResponseItem> GetApiv1MenuitemsidAsync(Dictionary<string, string> requestHeaders, Guid id);
    /// <remarks>
    /// GET /api/v1/menuitems/{id}/full
    /// </remarks>
    Task<FullMenuItemGetResponse> GetApiv1MenuitemsidfullAsync(Dictionary<string, string> requestHeaders, Guid id);
    /// <remarks>
    /// GET /api/v1/restaurants
    /// </remarks>
    Task<RestaurantGetResponse> GetApiv1RestaurantsAsync(Dictionary<string, string> requestHeaders);
    /// <remarks>
    /// POST /api/v1/restaurants
    /// </remarks>
    Task<RestaurantGetResponseItem> PostApiv1RestaurantsAsync(Dictionary<string, string> requestHeaders, RestaurantPostRequest apiv1RestaurantsPostRequest);
    /// <remarks>
    /// GET /api/v1/restaurants/{id}
    /// </remarks>
    Task<RestaurantGetResponseItem> GetApiv1RestaurantsidAsync(Dictionary<string, string> requestHeaders, Guid id);
    /// <remarks>
    /// DELETE /api/v1/restaurants/{id}
    /// </remarks>
    Task<string> DeleteApiv1RestaurantsidAsync(Dictionary<string, string> requestHeaders, Guid id);

}
