//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Flurl;
using Flurl.Http;
using SampleWebApiApi.Models;

namespace SampleWebApiApi;

/// <summary>
/// This is a sample web api for testing / demo purposes for Swagabond.
/// </summary>
public class SampleWebApiFlurlClient : ISampleWebApiClient
{
    private readonly string _baseUrl = string.Empty;

    public SampleWebApiFlurlClient(string baseUrl)
    {
        _baseUrl = baseUrl;
    }

    /// <remarks>
    /// GET /api/v1/franchises
    /// </remarks>
    public async Task<FranchiseGetResponseItem[]> GetApiv1FranchisesAsync(Dictionary<string, string> requestHeaders)
    {
        var path = "/api/v1/franchises";

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<FranchiseGetResponseItem[]>(response);

    }
    /// <remarks>
    /// GET /api/v1/franchises/{id}
    /// </remarks>
    public async Task<FranchiseGetResponseItem> GetApiv1FranchisesidAsync(Dictionary<string, string> requestHeaders, Guid id)
    {
        var path = "/api/v1/franchises/{id}";
        path = path.Replace("{id}", id.ToString(), StringComparison.OrdinalIgnoreCase);

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<FranchiseGetResponseItem>(response);

    }
    /// <remarks>
    /// GET /api/v1/menuitems
    /// </remarks>
    public async Task<MenuItemResponse> GetApiv1MenuitemsAsync(Dictionary<string, string> requestHeaders)
    {
        var path = "/api/v1/menuitems";

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<MenuItemResponse>(response);

    }
    /// <remarks>
    /// POST /api/v1/menuitems
    /// </remarks>
    public async Task<MenuItemResponseItem> PostApiv1MenuitemsAsync(Dictionary<string, string> requestHeaders, MenutItemPostRequest apiv1MenuitemsPostRequest)
    {
        var path = "/api/v1/menuitems";

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .PostAsync();

        return await DeserializeFlurlResponse<MenuItemResponseItem>(response);

    }
    /// <remarks>
    /// GET /api/v1/menuitems/{id}
    /// </remarks>
    public async Task<MenuItemResponseItem> GetApiv1MenuitemsidAsync(Dictionary<string, string> requestHeaders, Guid id)
    {
        var path = "/api/v1/menuitems/{id}";
        path = path.Replace("{id}", id.ToString(), StringComparison.OrdinalIgnoreCase);

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<MenuItemResponseItem>(response);

    }
    /// <remarks>
    /// GET /api/v1/menuitems/{id}/full
    /// </remarks>
    public async Task<FullMenuItemGetResponse> GetApiv1MenuitemsidfullAsync(Dictionary<string, string> requestHeaders, Guid id)
    {
        var path = "/api/v1/menuitems/{id}/full";
        path = path.Replace("{id}", id.ToString(), StringComparison.OrdinalIgnoreCase);

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<FullMenuItemGetResponse>(response);

    }
    /// <remarks>
    /// GET /api/v1/restaurants
    /// </remarks>
    public async Task<RestaurantGetResponse> GetApiv1RestaurantsAsync(Dictionary<string, string> requestHeaders)
    {
        var path = "/api/v1/restaurants";

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<RestaurantGetResponse>(response);

    }
    /// <remarks>
    /// POST /api/v1/restaurants
    /// </remarks>
    public async Task<RestaurantGetResponseItem> PostApiv1RestaurantsAsync(Dictionary<string, string> requestHeaders, RestaurantPostRequest apiv1RestaurantsPostRequest)
    {
        var path = "/api/v1/restaurants";

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .PostAsync();

        return await DeserializeFlurlResponse<RestaurantGetResponseItem>(response);

    }
    /// <remarks>
    /// GET /api/v1/restaurants/{id}
    /// </remarks>
    public async Task<RestaurantGetResponseItem> GetApiv1RestaurantsidAsync(Dictionary<string, string> requestHeaders, Guid id)
    {
        var path = "/api/v1/restaurants/{id}";
        path = path.Replace("{id}", id.ToString(), StringComparison.OrdinalIgnoreCase);

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<RestaurantGetResponseItem>(response);

    }
    /// <remarks>
    /// DELETE /api/v1/restaurants/{id}
    /// </remarks>
    public async Task<string> DeleteApiv1RestaurantsidAsync(Dictionary<string, string> requestHeaders, Guid id)
    {
        var path = "/api/v1/restaurants/{id}";
        path = path.Replace("{id}", id.ToString(), StringComparison.OrdinalIgnoreCase);

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .DeleteAsync();

        return await DeserializeFlurlResponse<string>(response);

    }


    /// <summary>
    /// Deserializes a FlurlResponse as the proper type <typeparam="T"/>
    /// </summary>
    private static async Task<T> DeserializeFlurlResponse<T>(IFlurlResponse response)
    {
        // if T is string return getstringasync
        if (typeof(T) == typeof(string))
        {
            return (T)(object)(await response.GetStringAsync());
        }
        else
        {
            return await response.GetJsonAsync<T>();
        }
    }



}
