//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using SampleWebApiApi.Models;

namespace SampleWebApiApi;

/// <summary>
/// /// This is a sample web api for testing / demo purposes for Swagabond.
/// </summary>
public interface ISampleWebApiClient
{
    /// <remarks>
    /// GET /api/v1/franchises
    /// </remarks>
    Task<SamplewebapiControllersFranchisegetresponseitem[]> GetApiV1FranchisesAsync(Dictionary<string, string> requestHeaders);
    /// <remarks>
    /// GET /api/v1/franchises/{id}
    /// </remarks>
    Task<SamplewebapiControllersFranchisegetresponseitem> GetApiV1FranchisesidAsync(Dictionary<string, string> requestHeaders, Guid id);
    /// <remarks>
    /// GET /api/v1/menuitems
    /// </remarks>
    Task<SamplewebapiControllersMenuitemresponse> GetApiV1MenuitemsAsync(Dictionary<string, string> requestHeaders);
    /// <remarks>
    /// POST /api/v1/menuitems
    /// </remarks>
    Task<SamplewebapiControllersMenuitemresponseitem> PostApiV1MenuitemsAsync(Dictionary<string, string> requestHeaders, SamplewebapiControllersMenutitempostrequest apiV1MenuitemsPostRequest);
    /// <remarks>
    /// GET /api/v1/menuitems/{id}
    /// </remarks>
    Task<SamplewebapiControllersMenuitemresponseitem> GetApiV1MenuitemsidAsync(Dictionary<string, string> requestHeaders, Guid id);
    /// <remarks>
    /// GET /api/v1/menuitems/{id}/full
    /// </remarks>
    Task<SamplewebapiControllersFullmenuitemgetresponse> GetApiV1MenuitemsidFullAsync(Dictionary<string, string> requestHeaders, Guid id);
    /// <remarks>
    /// GET /api/v1/restaurants
    /// </remarks>
    Task<SamplewebapiControllersRestaurantgetresponse> GetApiV1RestaurantsAsync(Dictionary<string, string> requestHeaders);
    /// <remarks>
    /// POST /api/v1/restaurants
    /// </remarks>
    Task<SamplewebapiControllersRestaurantgetresponseitem> PostApiV1RestaurantsAsync(Dictionary<string, string> requestHeaders, SamplewebapiControllersRestaurantpostrequest apiV1RestaurantsPostRequest);
    /// <remarks>
    /// GET /api/v1/restaurants/{id}
    /// </remarks>
    Task<SamplewebapiControllersRestaurantgetresponseitem> GetApiV1RestaurantsidAsync(Dictionary<string, string> requestHeaders, Guid id);
    /// <remarks>
    /// DELETE /api/v1/restaurants/{id}
    /// </remarks>
    Task<string> DeleteApiV1RestaurantsidAsync(Dictionary<string, string> requestHeaders, Guid id);

}
