//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
//
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Flurl;
using Flurl.Http;
using SampleWebApiApi.Models;

namespace SampleWebApiApi;

/// <summary>
/// /// This is a sample web api for testing / demo purposes for Swagabond.
/// </summary>
public class SampleWebApiFlurlClient : ISampleWebApiClient
{
    private readonly string _baseUrl = string.Empty;

    public SampleWebApiFlurlClient(string baseUrl)
    {
        _baseUrl = baseUrl;
    }

    /// <remarks>
    /// GET /api/v1/franchises
    /// </remarks>
    public async Task<SamplewebapiControllersFranchisegetresponseitem[]> GetApiV1FranchisesAsync(Dictionary<string, string> requestHeaders)
    {
        var path = "/api/v1/franchises";

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<SamplewebapiControllersFranchisegetresponseitem[]>(response);

    }
    /// <remarks>
    /// GET /api/v1/franchises/{id}
    /// </remarks>
    public async Task<SamplewebapiControllersFranchisegetresponseitem> GetApiV1FranchisesidAsync(Dictionary<string, string> requestHeaders, Guid id)
    {
        var path = "/api/v1/franchises/{id}";
        path = path.Replace("{id}", id.ToString(), StringComparison.OrdinalIgnoreCase);

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<SamplewebapiControllersFranchisegetresponseitem>(response);

    }
    /// <remarks>
    /// GET /api/v1/menuitems
    /// </remarks>
    public async Task<SamplewebapiControllersMenuitemresponse> GetApiV1MenuitemsAsync(Dictionary<string, string> requestHeaders)
    {
        var path = "/api/v1/menuitems";

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<SamplewebapiControllersMenuitemresponse>(response);

    }
    /// <remarks>
    /// POST /api/v1/menuitems
    /// </remarks>
    public async Task<SamplewebapiControllersMenuitemresponseitem> PostApiV1MenuitemsAsync(Dictionary<string, string> requestHeaders, SamplewebapiControllersMenutitempostrequest apiV1MenuitemsPostRequest)
    {
        var path = "/api/v1/menuitems";

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .PostAsync();

        return await DeserializeFlurlResponse<SamplewebapiControllersMenuitemresponseitem>(response);

    }
    /// <remarks>
    /// GET /api/v1/menuitems/{id}
    /// </remarks>
    public async Task<SamplewebapiControllersMenuitemresponseitem> GetApiV1MenuitemsidAsync(Dictionary<string, string> requestHeaders, Guid id)
    {
        var path = "/api/v1/menuitems/{id}";
        path = path.Replace("{id}", id.ToString(), StringComparison.OrdinalIgnoreCase);

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<SamplewebapiControllersMenuitemresponseitem>(response);

    }
    /// <remarks>
    /// GET /api/v1/menuitems/{id}/full
    /// </remarks>
    public async Task<SamplewebapiControllersFullmenuitemgetresponse> GetApiV1MenuitemsidFullAsync(Dictionary<string, string> requestHeaders, Guid id)
    {
        var path = "/api/v1/menuitems/{id}/full";
        path = path.Replace("{id}", id.ToString(), StringComparison.OrdinalIgnoreCase);

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<SamplewebapiControllersFullmenuitemgetresponse>(response);

    }
    /// <remarks>
    /// GET /api/v1/restaurants
    /// </remarks>
    public async Task<SamplewebapiControllersRestaurantgetresponse> GetApiV1RestaurantsAsync(Dictionary<string, string> requestHeaders)
    {
        var path = "/api/v1/restaurants";

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<SamplewebapiControllersRestaurantgetresponse>(response);

    }
    /// <remarks>
    /// POST /api/v1/restaurants
    /// </remarks>
    public async Task<SamplewebapiControllersRestaurantgetresponseitem> PostApiV1RestaurantsAsync(Dictionary<string, string> requestHeaders, SamplewebapiControllersRestaurantpostrequest apiV1RestaurantsPostRequest)
    {
        var path = "/api/v1/restaurants";

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .PostAsync();

        return await DeserializeFlurlResponse<SamplewebapiControllersRestaurantgetresponseitem>(response);

    }
    /// <remarks>
    /// GET /api/v1/restaurants/{id}
    /// </remarks>
    public async Task<SamplewebapiControllersRestaurantgetresponseitem> GetApiV1RestaurantsidAsync(Dictionary<string, string> requestHeaders, Guid id)
    {
        var path = "/api/v1/restaurants/{id}";
        path = path.Replace("{id}", id.ToString(), StringComparison.OrdinalIgnoreCase);

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .GetAsync();

        return await DeserializeFlurlResponse<SamplewebapiControllersRestaurantgetresponseitem>(response);

    }
    /// <remarks>
    /// DELETE /api/v1/restaurants/{id}
    /// </remarks>
    public async Task<string> DeleteApiV1RestaurantsidAsync(Dictionary<string, string> requestHeaders, Guid id)
    {
        var path = "/api/v1/restaurants/{id}";
        path = path.Replace("{id}", id.ToString(), StringComparison.OrdinalIgnoreCase);

        var response = await _baseUrl
            .AppendPathSegment(path)
            .WithHeaders(requestHeaders)
            .DeleteAsync();

        return await DeserializeFlurlResponse<string>(response);

    }


    /// <summary>
    /// Deserializes a FlurlResponse as the proper type <typeparam="T"/>
    /// </summary>
    private static async Task<T> DeserializeFlurlResponse<T>(IFlurlResponse response)
    {
        // if T is string return getstringasync
        if (typeof(T) == typeof(string))
        {
            return (T)(object)(await response.GetStringAsync());
        }
        else
        {
            return await response.GetJsonAsync<T>();
        }
    }



}
