# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Restore tools
      run: dotnet tool restore

    - name: Build Main Solution
      run: dotnet build ./src/Swagabond.sln --no-restore

    - name: Build Utility Projects
      run: dotnet build ./utilities/Swagutils/Swagutils.sln --no-restore

    - name: UnitTests
      run: dotnet test ./src/Swagabond.Tests

    - name: IntegrationTests
      run: dotnet test ./src/Swagabond.IntegrationTests
