# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies for main solution
      run: dotnet restore ./src/Swagabond.sln
      
    - name: Restore tools for main solution
      run: dotnet tool restore 
      working-directory: ./src

    - name: Build Main Solution
      run: dotnet build ./src/Swagabond.sln --no-restore

    - name: Restore dependencies for utility projects
      run: dotnet restore ./utilities/Swagutils/Swagutils.sln

    - name: Restore tools for utility projects
      run: dotnet tool restore
      working-directory: ./utilities/Swagutils

    - name: Build Utility Projects
      run: dotnet build ./utilities/Swagutils/Swagutils.sln --no-restore

    - name: UnitTests
      run: dotnet test ./src/Swagabond.Tests

    - name: Build IntegrationTests
      run: dotnet build ./src/Swagabond.IntegrationTests/Swagabond.IntegrationTests.csproj

    - name: Manually copy swagger files to output
      run: |
        mkdir -p ./src/Swagabond.IntegrationTests/bin/Debug/net8.0/SwaggerFiles/
        cp ./src/Swagabond.IntegrationTests/SwaggerFiles/*.json ./src/Swagabond.IntegrationTests/bin/Debug/net8.0/SwaggerFiles/

    - name: IntegrationTests
      run: dotnet test ./src/Swagabond.IntegrationTests
